version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: todo-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: khadija
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - todo-network
    restart: unless-stopped

  backend:
    image: khadija2557/backend-app:latest
    container_name: todo-backend
    environment:
      - MONGODB_URI=mongodb://khadija:12345@mongodb:27017/TODO?authSource=admin
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - todo-network
    restart: unless-stopped

  frontend:
    image: khadija2557/frontend-app:latest
    container_name: todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todo-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  todo-network:
    driver: bridge
